### PR TITLE
feat: add safe connector to defaultWagmiCoreConfig

### LINKED ISSUE #2483: [feature] config options for adding safe connector in defaultWagmiConfig
### What problem does this new feature solve?

Currently as it stands we have to use wagmi's createConfig in order to use safe connector with web3modal. If a developer wants to use embedded wallets in addition to enabling safe connector so their app is Safe App enabled then it's not possible given the current config setup.

### Describe the solution you'd like

I propose adding an optional field in defaultWagmiConfig to 'enableSafe' connector as well as another optional RegExp[] field for allowedDomains.

### PR DESCRIPTION
**Pull request by ChewySwap**
add safe connector and allowedDomains setting to defaultWagmiCoreConfig and defaultWagmiReactConfig

# Description

Please include a brief summary of the change.

## Type of change

- [ ] Chore (non-breaking change that addresses non-functional tasks, maintenance, or code quality improvements)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Associated Issues

For GH issues: closes #2483

# Showcase (Optional)

If there is a UI change include the screenshots with before and after state.
If new feature is being introduced, include the link to demo recording.

# Checklist

- [ ] Code in this PR is covered by automated tests (Unit tests, E2E tests)
- [ ] My changes generate no new warnings
- [ ] I have reviewed my own code
- [ ] I have filled out all required sections

### CODE REVIEW

**Comment by glitch-txs** [comment]
Thanks!

Could you run prettier? `npm run prettier:format`

**Comment by ChewySwap** [comment]
> Thanks!
> 
> Could you run prettier? `npm run prettier:format`

sure thing!

**Comment by enesozturk** [comment]
Screenshot 2024-08-16 at 16 58 54

I'm getting Safe connector even though I don't have Safe extension installed

**Comment by enesozturk** [comment]
Closing this due to low activity and there is no request on having the Safe connector by default. For the future visitors who is looking for Safe connector, you can still pass the `safe` connector to the `WagmiAdapter` constructor, like the following:

```js
import { safe } from '@wagmi/connectors'

..

const wagmiAdapter = new WagmiAdapter({
   ...otherProps,
   connectors: [safe()]
})
```

**Pull request closed without merging**
