### PR TITLE
fix: return custom rpc instead walletconnect rpc

### PR DESCRIPTION
**Pull request by j4w3ny**
# Description

This is to fix a small bug in `@reown/appkit-utils` which will replace user-defined rpc with WalletConnect rpc.

## Type of change

- [ ] Chore (non-breaking change that addresses non-functional tasks, maintenance, or code quality improvements)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Associated Issues

No issue was associated with this PR.

# Checklist

- [ ] Code in this PR is covered by automated tests (Unit tests, E2E tests)
- [ ] My changes generate no new warnings
- [ ] I have reviewed my own code
- [ ] I have filled out all required sections
- [ ] I have tested my changes on the preview link
- [ ] Approver of this PR confirms that the changes are tested on the preview link

### CODE REVIEW

**Review by arein — COMMENTED** [review]
thank you @j4w3ny - can you add a test to cover regressions?

**Review by j4w3ny — COMMENTED** [review]
> thank you @j4w3ny - can you add a test to cover regressions? 

yeah i can but can you be more specific on this? I dont get the meaning of "regression" here.

**Review by svenvoskamp — APPROVED** [review]

**Comment by arein** [comment]
Just a test making sure that in a future refactor we don't "regress" and reintroduce the bug

**Comment by j4w3ny** [comment]
> Just a test making sure that in a future refactor we don't "regress" and reintroduce the bug

test is now added. i also add a `useWalletConnectRpc` option in the constructor so user can choose to opt-in. (if the parameter not provided, it will returns the defaultRpcUrl by default)

**Comment by j4w3ny** [comment]
Hello. What's the progress on this pr?

**Comment by svenvoskamp** [comment]
@j4w3ny Thanks for the PR. We changed the name of the parameter. Closing this PR as we followed up with this PR with some extra changes. If you have questions, please ask them here -> https://github.com/reown-com/appkit/pull/3418

**Pull request closed without merging**
