### PR TITLE
request: Added "optimismSepolia" network for Testnet

### PR DESCRIPTION
**Pull request by nidz-the-fact**
# Description

Added "optimismSepolia" network for Testnet

## Type of change

- [ ] Chore (non-breaking change that addresses non-functional tasks, maintenance, or code quality improvements)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Associated Issues

_None_

# Showcase (Optional)

_None_

# Checklist

- [ ] Code in this PR is covered by automated tests (Unit tests, E2E tests)
- [ ] My changes generate no new warnings
- [ ] I have reviewed my own code
- [x] I have filled out all required sections
- [ ] I have tested my changes on the preview link
- [ ] Approver of this PR confirms that the changes are tested on the preview link

### CODE REVIEW

**Comment by enesozturk** [comment]
@nidz-the-fact LGTM - thanks for the contribution. One request: could you run `pnpm changeset` script and create changeset file and push to PR? For questions:
- Select all packages (changed or not changed)
- Not major
- Not minor
- Give a short description that starts with a verb like "Add Optimisim Sepolia to exported networks)

Thanks!

**Review by enesozturk — APPROVED** [review]
Approved - just changeset files please @nidz-the-fact

**Comment by nidz-the-fact** [comment]
> Approved - just changeset files please @nidz-the-fact

I have followed your instructions to add the files. Is it correct? **Please check again**. @enesozturk  _Thank you_. 
image

**Comment by enesozturk** [comment]
@

> > Approved - just changeset files please @nidz-the-fact
> 
> I have followed your instructions to add the files. Is it correct? **Please check again**. @enesozturk _Thank you_. image

@nidz-the-fact No, it's not meeting the requirements that I mentioned above:

> Select all packages (changed or not changed)
> Not major
> Not minor
> Give a short description that starts with a verb like "Add Optimisim Sepolia to exported networks)

**Comment by nidz-the-fact** [comment]
> @
> 
> > > Approved - just changeset files please @nidz-the-fact
> > 
> > 
> > I have followed your instructions to add the files. Is it correct? **Please check again**. @enesozturk _Thank you_. image
> 
> @nidz-the-fact No, it's not meeting the requirements that I mentioned above:
> 
> > Select all packages (changed or not changed)
> > Not major
> > Not minor
> > Give a short description that starts with a verb like "Add Optimisim Sepolia to exported networks)

Is this what I chose and did in 3 steps? @enesozturk 
image
image
image

**Comment by enesozturk** [comment]
@nidz-the-fact In step 2, just press enter - do shouldn't select anything :)

**Comment by nidz-the-fact** [comment]
> @nidz-the-fact In step 2, just press enter - you shouldn't select anything :)

I press enter and cannot skip the option. @enesozturk 
image

**Comment by nidz-the-fact** [comment]
Is this correct? @enesozturk 
image

**Comment by enesozturk** [comment]
Hey @nidz-the-fact, thank you for your contribution. Since we started using Viem chains by default, `optimismSepolia` is already supported by `@reown/appkit/networks`. You can import like the following:

```js
import { optimismSepolia } from '@reown/appkit/networks'
```

Closing your PR and appreciate the contribution 🙏🏽

**Pull request closed without merging**
