### PR TITLE
adding base sepolia support for wagmi permission tests

### PR DESCRIPTION
**Pull request by KannuSingh**
# Description

- Enable ERC7715 permissions test on `baseSepolia`
- Enabled signing and sending the userOp using the granted permissions via WalletService/UserOpBuilder service [previously it was also calling co-signer service]

## Type of change

- [x] Chore (non-breaking change that addresses non-functional tasks, maintenance, or code quality improvements)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Associated Issues

For Linear issues: Closes APKT-xxx
For GH issues: closes #...

# Showcase (Optional)

If there is a UI change include the screenshots with before and after state.
If new feature is being introduced, include the link to demo recording.

# Checklist

- [x] Code in this PR is covered by automated tests (Unit tests, E2E tests)
- [x] My changes generate no new warnings
- [x] I have reviewed my own code
- [x] I have filled out all required sections

### CODE REVIEW

**Review by lukaisailovic — APPROVED** [review]
Will this work with both sepolia and base-sepolia?

**Comment by KannuSingh** [comment]
Yes, I deployed the Donut contract using Create2 so it will be using the same address.

**Comment by lukaisailovic** [comment]
@KannuSingh Should we merge this or?

**Comment by KannuSingh** [comment]
[PR](https://github.com/reown-com/appkit/pull/2875) supersedes this one, so we can go ahead and close it.

**Pull request closed without merging**
